# Generated by Django 5.2.6 on 2025-09-25 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('federal', 'Federal'), ('estadual', 'Estadual'), ('municipal', 'Municipal'), ('trabalhista', 'Trabalhista')], max_length=20)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Análise'), ('completed', 'Concluída'), ('overdue', 'Vencida')], default='pending', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
